import React, { useState } from 'react';
import { decryptImage } from '../services/api';
import { Upload, FileKey, Loader, ShieldCheck, AlertCircle } from 'lucide-react';

const DecryptImage = () => {
  const [file, setFile] = useState(null);
  const [passkey, setPasskey] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [preview, setPreview] = useState(null);

  const handleFileChange = (e) => {
    const selected = e.target.files[0];
    if (selected) {
      setFile(selected);
      setPreview(URL.createObjectURL(selected));
      setResult(null);
      setError(null);
    }
  };

  const handleDecrypt = async () => {
    if (!file) {
      setError("Please upload an image.");
      return;
    }
    if (!passkey.trim()) {
      setError("Please enter the decryption passkey.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const data = await decryptImage(file, passkey);
      setResult(data.data);
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to decrypt image. The key might be invalid.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div>
        <h2 className="text-4xl font-black mb-4 tracking-tight">Manual Decryption</h2>
        <p className="text-gray-400 text-lg max-w-2xl">
          Upload any steganographic image generated by this system to extract and decrypt its hidden AES-256 payload.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="glass-card p-8 flex flex-col items-center justify-center min-h-[400px]">
          {!preview ? (
            <label className="w-full h-full flex flex-col items-center justify-center border-2 border-dashed border-gray-600 rounded-xl hover:border-accent hover:bg-accent/5 transition-all cursor-pointer group">
              <div className="p-4 bg-gray-800 rounded-full group-hover:bg-accent/20 transition-colors mb-4">
                <Upload className="w-8 h-8 text-gray-400 group-hover:text-accent transition-colors" />
              </div>
              <p className="text-gray-300 font-medium">Click or drag image to upload</p>
              <p className="text-sm text-gray-500 mt-2">PNG format required for LSB extraction</p>
              <input type="file" accept="image/png" className="hidden" onChange={handleFileChange} />
            </label>
          ) : (
            <div className="w-full space-y-6">
              <div className="relative rounded-xl overflow-hidden border border-white/10 group">
                <img src={preview} alt="Preview" className="w-full h-64 object-cover" />
                <div className="absolute inset-0 bg-black/60 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <label className="cursor-pointer bg-white/10 hover:bg-white/20 backdrop-blur px-4 py-2 rounded-lg font-medium transition-colors">
                    Change Image
                    <input type="file" accept="image/png" className="hidden" onChange={handleFileChange} />
                  </label>
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-300 mb-2 uppercase tracking-wider">Passkey</label>
                <input 
                  type="text" 
                  placeholder="Enter decryption key..."
                  className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-600 focus:outline-none focus:border-accent transition-all font-mono"
                  value={passkey}
                  onChange={e => setPasskey(e.target.value)}
                />
              </div>

              <button
                onClick={handleDecrypt}
                disabled={loading || !passkey}
                className="w-full bg-gradient-to-r from-accent to-[#00cc7a] hover:from-[#00e67a] hover:to-[#00b36b] text-black font-bold py-4 px-6 rounded-xl transition-all shadow-[0_0_20px_rgba(0,255,136,0.3)] hover:shadow-[0_0_30px_rgba(0,255,136,0.5)] flex justify-center items-center transform hover:-translate-y-1"
              >
                {loading ? <Loader className="animate-spin w-6 h-6" /> : <><FileKey className="w-6 h-6 mr-2" /> Extract & Decrypt</>}
              </button>
            </div>
          )}
        </div>

        <div className="glass-card p-8 flex flex-col relative overflow-hidden">
          {error && (
            <div className="absolute inset-0 bg-danger/10 backdrop-blur-md flex flex-col items-center justify-center p-8 text-center animate-fade-in z-10">
              <AlertCircle className="w-16 h-16 text-danger mb-4" />
              <h3 className="text-2xl font-bold text-white mb-2">Decryption Failed</h3>
              <p className="text-red-200">{error}</p>
              <button onClick={() => setError(null)} className="mt-6 px-6 py-2 border border-danger/50 rounded-lg hover:bg-danger/20 transition-colors">Try Again</button>
            </div>
          )}

          {result ? (
            <div className="animate-fade-in h-full flex flex-col">
              <div className="flex items-center space-x-3 mb-6 pb-6 border-b border-white/10">
                <div className="p-3 bg-accent/20 rounded-full"><ShieldCheck className="w-8 h-8 text-accent" /></div>
                <div>
                  <h3 className="text-2xl font-bold text-white">Payload Decrypted</h3>
                  <p className="text-sm text-accent font-mono mt-1">AES-256 Signature Verified</p>
                </div>
              </div>
              <div className="flex-1 bg-black/40 rounded-xl p-6 border border-white/5 overflow-auto custom-scrollbar">
                <pre className="text-green-400 font-mono text-sm leading-relaxed">
                  {JSON.stringify(result, null, 2)}
                </pre>
              </div>
            </div>
          ) : !error && (
            <div className="h-full flex flex-col items-center justify-center opacity-40 text-center">
              <FileKey className="w-16 h-16 text-gray-500 mb-6" />
              <h3 className="text-xl font-medium text-white mb-2">Awaiting Image</h3>
              <p className="text-gray-400 max-w-xs">Upload an image and run decryption to view the hidden payload here.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DecryptImage;
